apiVersion: apps/v1
kind: Deployment
metadata:
  name: dari-backend
  labels:
    app: dari-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dari-backend
  template:
    metadata:
      labels:
        app: dari-backend
    spec:
      containers:
      - name: dari-backend
        image: hibafh/dari-backend
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: jdbc:mysql://dari-mysql:3306/bootdb?allowPublicKeyRetrieval=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME         
          value: root
        -name: SPRING_DATASOURCE_USERNAME
          value: root
          
        

---
apiVersion: v1
kind: Service
metadata:
  name: dari-backend-service
spec:
  selector:
    app: dari-backend
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
