apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dari-front
  labels:
    app: dari-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dari-front
  template:
    metadata:
      labels:
        app: dari-front
    spec:
      containers:
      - name: dari-front
        image: hibafh/dari-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dari-front-service
spec:
  selector:
    app: dari-front
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30002
